# This file was generated by GoReleaser. DO NOT EDIT.
cask "bento" do
  name "bento"
  desc "Portable agent workspaces. Save, ship, restore."
  homepage "https://github.com/kajogo777/bento"
  version "0.1.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bento"

  on_macos do
    on_intel do
      url "https://github.com/kajogo777/bento/releases/download/v#{version}/bento_#{version}_darwin_amd64.tar.gz"
      sha256 "9a7cce347f1923a430d32d3ab00d6f53ecda8c9cdc1141598266f43ac0e49b6b"
    end
    on_arm do
      url "https://github.com/kajogo777/bento/releases/download/v#{version}/bento_#{version}_darwin_arm64.tar.gz"
      sha256 "2844104daa8626faa9dbfc9d7a99fcdbbb399dae7ac68842c1834c9938653f39"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kajogo777/bento/releases/download/v#{version}/bento_#{version}_linux_amd64.tar.gz"
      sha256 "074bc90b4fe97b956f15e79f6517e2e41f8bf9a9565ea36fd17db7f975e5982f"
    end
    on_arm do
      url "https://github.com/kajogo777/bento/releases/download/v#{version}/bento_#{version}_linux_arm64.tar.gz"
      sha256 "e5e03297f433c7a5c67f1b626338783073af0f528918ba67d0ad5e75d27ff681"
    end
  end

  # No zap stanza required
end
