# This file was generated by GoReleaser. DO NOT EDIT.
cask "bento" do
  name "bento"
  desc "Portable agent workspaces. Save, ship, restore."
  homepage "https://github.com/kajogo777/bento"
  version "0.1.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bento"

  on_macos do
    on_intel do
      url "https://github.com/kajogo777/bento/releases/download/v#{version}/bento_#{version}_darwin_amd64.tar.gz"
      sha256 "71ffe62482b0e891a2ad9dbeb87beeac80f8585732b1dc079e013c44e4275db4"
    end
    on_arm do
      url "https://github.com/kajogo777/bento/releases/download/v#{version}/bento_#{version}_darwin_arm64.tar.gz"
      sha256 "45e5b4014bf5c0255e179e137b81d2ecea0ec14f26a6048f5ae318e8f17baa8f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kajogo777/bento/releases/download/v#{version}/bento_#{version}_linux_amd64.tar.gz"
      sha256 "8002b878bd13a9a3af35ebb2703d253b5bba80b1bcf68f81c3544a0aabc8763c"
    end
    on_arm do
      url "https://github.com/kajogo777/bento/releases/download/v#{version}/bento_#{version}_linux_arm64.tar.gz"
      sha256 "cd04eb00606adccf955ca975ce2d8438c993d5359cbbc7294688ca2d9b987119"
    end
  end

  # No zap stanza required
end
