# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bento < Formula
  desc "Portable agent workspaces. Save, ship, restore."
  homepage "https://github.com/kajogo777/bento"
  version "0.1.43"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kajogo777/bento/releases/download/v0.1.43/bento_0.1.43_darwin_amd64.tar.gz"
      sha256 "e9354ccfa8071e812a446dcd0ebdee049b69888d1409d4293893b7739934c868"

      define_method(:install) do
        bin.install "bento"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kajogo777/bento/releases/download/v0.1.43/bento_0.1.43_darwin_arm64.tar.gz"
      sha256 "c04f4a71532c50e679efa952e6977dc398ce3026e1110062b619cd920984c859"

      define_method(:install) do
        bin.install "bento"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kajogo777/bento/releases/download/v0.1.43/bento_0.1.43_linux_amd64.tar.gz"
      sha256 "a8884d1fd6a83bee66d17b32b6d35d9c9135f089f0606ce348a7f8a80ef284e9"
      define_method(:install) do
        bin.install "bento"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kajogo777/bento/releases/download/v0.1.43/bento_0.1.43_linux_arm64.tar.gz"
      sha256 "34fcef43236f9264b220d6aa3d3d31ed79789e9a93096dd4b50266e8ebe0bc09"
      define_method(:install) do
        bin.install "bento"
      end
    end
  end
end
